### ISSUE TITLE
package control

### ISSUE THREAD

**Issue by inlife** [iAmRoland/Sublime-Squirrel#1]
hey
what do you need to publish this project to package control repository ?

**Comment by iAmRoland** [comment]
Hello!
There are couple of things to do, here is a list if you're intrested:
https://packagecontrol.io/docs/submitting_a_package
Don't have time to do this right now, but will try to get it up there later, unless someone does it before me.

**Comment by inlife** [comment]
i checked the list, everything looks ok!
if it's not very hard for you, could you please tag latest commit with `1.0.0` ?

in other case (you dont have time at all/smth other) would you give me permission to fork your repo and tag it
also you can add me as a **maintainer** to this repo.

ill make the rest (forking https://github.com/wbond/package_control_channel, and adding this package)
i think that `squirrel` will be a good package name 😉

**Comment by iAmRoland** [comment]
Alright, I took a little time and fixed it :smile: 
I have made a pull request, it passed all checks, so hopefully it should be available via Package Control soon.

**Comment by iAmRoland** [comment]
Oh lol, just saw you did it as well :smile:

**Comment by inlife** [comment]
yep :D
in that i will remove my pull request )

**Comment by inlife** [comment]
also, seems like you have different configured emails for git and github
![image](https://cloud.githubusercontent.com/assets/2182108/18631462/c817d1d6-7e7a-11e6-83a5-09cd373beb5d.png)

And thanks for your time !
Much appreciated. 🐱
